name: 'Go pull request message linter'
description: 'Inspect pull request messages with the format "<type>(scope): <subject>".'
runs:
  using: 'composite'
  steps:
    - run: |
        curl -Lo go-commitlinter.tar.gz https://github.com/masahiro331/go-commitlinter/releases/download/0.0.2/go-commitlinter_0.0.2_Linux_x86_64.tar.gz
        tar xvfz go-commitlinter.tar.gz
        mv go-commitlinter /usr/local/bin/
      shell: bash
    - run: gh pr view $PR | head -n 1  | cut -f 2 | go-commitlinter
      shell: bash
